#!/bin/bash

clang main.c                        \
  -o vips-scale                     \
  -I/opt/local/include/glib-2.0     \
  -I/opt/local/lib/glib-2.0/include \
  -lvips                            \
  -lglib-2.0                        \
  -lgobject-2.0                     \

